### ISSUE TITLE
Soft_WPMI returning more than one. 

### ISSUE THREAD

**Issue by EricFerreiraS** [Trustworthy-ML-Lab/CLIP-dissect#1]
Congrats on the excellent work developed, folks!

I've tried to use the approach to different datasets/models/concepts, and the code runs ok, but when I evaluate the similarities, I got values over one. 
I ran some experiments:
### Try 1
 - dataset_probe: Action40
 - number concepts: 191
 - model: Resnet_152 and Inception_V3
### Try 2
- dataset_probe: Action40 + Imagenet + Broden
- number concepts: 2388
- model: Resnet_152 and Inception_V3
And other variations, using different CLIP models as well. 

The only way the similarity results come between [0,1] is when I use/combine the 20k concepts to extract the values. Is there a relation between the number of concepts and model size? Am I missing something?

**Comment by tuomaso** [comment]
Thanks for the feedback! This is actually not an issue, the softWPMI function is not required to only return values in the [0,1] range. It is a variant of pointwise mutual information, and as such can also return negative numbers or values greater than one. However since we take the max over concepts it is usually always positive. Typically the range of similarities changes with the model size and concept set size, and larger concept sets lead to smaller similarities. As such we recommend to mostly compare similarity values only within the same setup, i.e. to find most explainable neurons in a network.
